title: Daniel Bentzon
description: Skriverier, indsigter og digte
lang: da
url: ""
baseurl: ""
markdown: kramdown
timezone: Europe/Copenhagen

collections:
  sektioner:
    output: false
  sider:
    output: true
    permalink: /sider/:title/
  skriverier:
    output: true
    permalink: /skriverier/:title/

defaults:
  - scope:
      path: ""
      type: "sider"
    values:
      layout: page
  - scope:
      path: ""
      type: "skriverier"
    values:
      layout: skriverie
